### ISSUE TITLE
Suggested Improvements

### ISSUE THREAD

**Issue by nate-eisner** [ticketmaster/Android-SecureEntrySDK#1]
After integrating this SDK, I have some suggested improvements.

- Proper release delivery
  - A versioned `.aar` uploaded to either github or maven/jcenter/jitpack etc. This would prevent having to clone the repo locally just to build the library ourselves.

- Allow time syncing before the view is shown
  - It would be nice to see if there is some way to control time sync that isn't so coupled to the `SecureEntryView`
  - This time logic can be useful in other places
  - I currently have the `Clock` wrapped as a Dagger injected `@Singleton` so it can be used in other places and synced on app launch so it has the proper time before the user gets to the ticket

- Improved or customizable error state
  - Having an error states of `No token!` or `Invalid token!` is not very user friendly or good looking.
  - Maybe add in a way to put an image placeholder incase an error does occur?

- Animation controls
  - If the animations are not requirement for this integration, I would recommend adding a way to disable them.
  - Color customization is nice however, teams that are integrating this might feel this animation does not match their current design.

Let me know if you have questions on any of these. I am willing to contribute in anyway possible.

**Comment by kylejablonski** [comment]
@nate-eisner, For the last point above: To retain both testing and asset delivery integrity, no modifications to the barcode or animation are allowed. 

For point 2, we will be talking about exposing the time sync API outside the view and I will get back to you when we come up with a solution so each view will not be concerned with this functionality

**Comment by kylejablonski** [comment]
1. You can now obtain release 1.0.4 from jcenter 
2. We have provided the syncTime method to allow syncing the time ahead of view instantiation. 
3. The error state has been updated and you can now provide an error message of your own either through the setter `setErrorText(String errorText)` or through xml
4. Customization of the animation will not be supported

You can read more about these updates in the [Readme.md](https://github.com/ticketmaster/Android-SecureEntrySDK/blob/master/README.md)
