### ISSUE TITLE
Graphical Flash of barcode when rendering static barcode.

### ISSUE THREAD

**Issue by gpowell13** [ticketmaster/Android-SecureEntrySDK#2]
SDK v. 1.0.4

Looks like the rotating barcode flashes when rendering a static barcode. See the screenshot below.

![screen shot 2019-03-04 at 12 54 28 pm](https://user-images.githubusercontent.com/18534850/53755719-df9d3700-3e7c-11e9-9342-2c80aa0bc45e.png)

I have a video of what is happening as well. Github doesn't like mp4s and converting to a GIF might not show the issue because of how fast it flashes.

**Comment by kylejablonski** [comment]
Hey Geoffrey, can you please share a gif either way. Or host the video somewhere and link it here?

**Comment by gpowell13** [comment]
So it seems the video has up and disappeared on my computer and we are having issues with the secure render api to reproduce. When those issues are resolved, I can add a comment with a video.

**Comment by kylejablonski** [comment]
Closing for now. Reopen if you are still experiencing this in the 1.5.0 release
