### ISSUE TITLE
Rotating Barcode rendering issues

### ISSUE THREAD

**Issue by nfagen1** [ticketmaster/Android-SecureEntrySDK#3]
SDK v. 1.0.4

1. On a rotating barcode the branded animated scan line gets stuck.
2. Barcode rending in a greyed out instance that is not valid. 

![69a6d0890c63](https://user-images.githubusercontent.com/30243061/53812898-05c8e280-3f22-11e9-8e4d-1f1260b73d79.gif)

 Have to reload tickets via the sdk to get them to render correctly:

![ed44864f851e](https://user-images.githubusercontent.com/30243061/53813308-f39b7400-3f22-11e9-9370-1e0f1ed46eee.gif)

**Comment by kylejablonski** [comment]
Hey Nick, in an attempt to reproduce the issue could you let me know if you are using a `LinearSnapHelper` or `PagerSnapHelper` on your `RecyclerView`

**Comment by gpowell13** [comment]
we are using `PagerSnapHelper` for our recycler view

**Comment by kylejablonski** [comment]
These issues should be fixed in 1.5.0 please reopen if you are still experiencing them.
