### ISSUE TITLE
SDK v. 1.0.4 not compatible with android OS 5.0

### ISSUE THREAD

**Issue by nfagen1** [ticketmaster/Android-SecureEntrySDK#4]
SDK crashes on start - all we can see is:

android.debug A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 5143 (s.android.debug)

![5 0](https://user-images.githubusercontent.com/30243061/53916246-478f8100-4027-11e9-9d86-e6bae8aa27af.gif)

**Comment by kylejablonski** [comment]
Thanks for reporting this. It will be fixed in the 1.0.5 release.
