### ISSUE TITLE
memory leak on v1.0.6

### ISSUE THREAD

**Issue by lucascgz** [ticketmaster/Android-SecureEntrySDK#6]
commit: 4f392440dd105f5e79566021e41307c446f0b146

launch Secure Entry Sample and press back to cause a leak and trigger a background heap dump.
see memory leak info in the following attachments: 

![Screenshot_1564390008](https://user-images.githubusercontent.com/20496107/62035014-98e01d00-b221-11e9-94b0-b8f2451df833.png)
![Screenshot_1564390001](https://user-images.githubusercontent.com/20496107/62035023-9bdb0d80-b221-11e9-9a52-a1b00d51813b.png)

**Comment by lucascgz** [comment]
Hi Secure Entry SDK team, could you please help take a look at this issue.
We're blocked.

**Comment by lucascgz** [comment]
still can reproduce on `v1.0.9`.
![Screenshot_1566893968](https://user-images.githubusercontent.com/20496107/63754024-bcf95180-c8e6-11e9-8741-574f390a387f.png)
![Screenshot_1566893955](https://user-images.githubusercontent.com/20496107/63754028-bff44200-c8e6-11e9-9690-b3a1f651e518.png)

**Comment by kylejablonski** [comment]
Fixed in the latest release 1.0.10
